/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Jcryptor;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        JcryptorCli classUnderTest = new JcryptorCli();
        assertEquals(0, classUnderTest.test());
    }
}
